vich_uploader:
    db_driver: orm

    mappings:
        property_image:
            url_prefix: /images/profil
            upload_destination: '%kernel.project_dir%/public/images/profil'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
